config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events
  resources :todos do
    member do
      get :start
      get :pause
      get :finish
      get :remove
      get :assign
      get :comment
    end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :todolist
  acts_as_list scope: :todolist

  belongs_to :project
  validates_presence_of :project
  validates_associated :project

  belongs_to :assignee, class_name:"User",foreign_key:'user_id'

  validates :body, presence: true

  # status
  # 0 paused
  # 1 started
  # 2 finished
  # 3 removed


  validates :status, inclusion: [nil,0,1,2,3]

  has_many :events, :as => :evetable
  has_many :comments, :as => :commentable

  def finishes
    self.status=2
    self.save!
  end

  def url
    "/todos/#{self.id}"
  end


end
class ActiveRecord::Base
  attr_accessor :touchedBy
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy,:start,:pause,:finish,:remove,:assign,:comment]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save

        Event.create!(creator:current_user,eventable:@todo,changed_attr:'id',new_value:@todo.id)
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end


  def start

    respond_to do |format|
      if @todo.update({status:1})
        Event.create!(creator:current_user,eventable:@todo,changed_attr:'status',new_value:1)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end


  def pause

    respond_to do |format|
      if @todo.update({status:0})
        Event.create!(creator:current_user,eventable:@todo,changed_attr:'status',new_value:0)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end



  def finish

    respond_to do |format|
      if @todo.update({status:2})
        Event.create!(creator:current_user,eventable:@todo,changed_attr:'status',new_value:2)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end



  def remove

    respond_to do |format|
      if @todo.update({status:3})
        Event.create!(creator:current_user,eventable:@todo,changed_attr:'status',new_value:3)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign
    new_params = params.require(:todo).permit(:user_id)
    new_user_id = new_params[:user_id]
    old_user_id = @todo.user_id.to_s
    respond_to do |format|
      if @todo.update(new_params)
        Event.create!(creator:current_user,eventable:@todo,changed_attr:'user_id',old_value:old_user_id,new_value:new_user_id) unless new_user_id==old_user_id
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end


  def comment

    comment = Comment.create!(body:'this is good',commentable:@todo)
    comment.attachments<<Attachment.new(name:'attachment1',url:'/files/1')
    comment.attachments<<Attachment.new(name:'attachment2',url:'/files/2')

    respond_to do |format|
      if comment.save
        Event.create!(creator:current_user,changed_attr:'comments',eventable:@todo,eventsource:comment)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def current_user
    User.first
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_params
    ps =  params.require(:todo).permit(:body)
    ps[:project_id]=1
    ps
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
    <% if @todo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

          <ul>
            <% @todo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_field :body%>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.body %> </td>
        <td><%= link_to 'Start', start_todo_path(todo) %></td>
        <td><%= link_to 'Pause', pause_todo_path(todo) %></td>
        <td><%= link_to 'Finish', finish_todo_path(todo) %></td>
        <td><%= link_to 'Remove', remove_todo_path(todo) %></td>
        <td><%= link_to 'Comment', comment_todo_path(todo) %></td>

        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>